
[alpha_vantage]
api_key = "WSFXHDXZK9N073TU"

[openai]
api_key = "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"
